global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fabric_orderer'
    static_configs:
      - targets: ['orderer.example.com:9443']

  - job_name: 'fabric_peer'
    static_configs:
      - targets: ['peer0.org1.example.com:9444']
